

services:
  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - PORT=3333
      - DATABASE_URL=mongodb://mongo_user:mongo_pass@mongo:27017/auth_db?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm run prisma:migrate && npm start"

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
     - DATABASE_URL=${DATABASE_URL}  # 👈 Pega do seu .env automaticamente
     -  JWT_SECRET=${JWT_SECRET}     # 👈 Adicione outras variáveis se necessário

volumes:
  mongodb_data: